version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    env_file: .env
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM dual;' | sqlplus -s ${SPRING_DATASOURCE_USERNAME}/${SPRING_DATASOURCE_PASSWORD}@//localhost:1521/FREEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10

  pluralis-app:
    build:
      context: .
    container_name: pluralis-app
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file: .env

volumes:
  oracle-data:
