version: "3.8"

services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    env_file: .env
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata

  pluralis-app:
    image: ${REGISTRY}/pluralis-app:${TAG}
    container_name: pluralis-app
    depends_on:
      oracle-db:
        condition: service_started
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/FREEPDB1

volumes:
  oracle-data:
