CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    gender VARCHAR2(50) NOT NULL,
    ethnicity VARCHAR2(50) NOT NULL,
    neurodivergent NUMBER(1) NOT NULL,
    lgbtqia NUMBER(1) NOT NULL
);

ALTER TABLE employees
    ADD CONSTRAINT pk_employees PRIMARY KEY (id);
