CREATE TABLE trainings (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    training_date DATE NOT NULL,
    mandatory NUMBER(1) NOT NULL
);

ALTER TABLE trainings
    ADD CONSTRAINT pk_trainings PRIMARY KEY (id);
