CREATE TABLE training_participations (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_id NUMBER NOT NULL,
    training_id NUMBER NOT NULL,
    completed NUMBER(1) NOT NULL
);

ALTER TABLE training_participations
    ADD CONSTRAINT pk_training_participations PRIMARY KEY (id);

ALTER TABLE training_participations
    ADD CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employees(id);

ALTER TABLE training_participations
    ADD CONSTRAINT fk_training FOREIGN KEY (training_id) REFERENCES trainings(id);
