CREATE TABLE anonymous_feedback (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    message VARCHAR2(500) NOT NULL,
    sent_date DATE DEFAULT SYSDATE
);

ALTER TABLE anonymous_feedback
    ADD CONSTRAINT pk_anonymous_feedback PRIMARY KEY (id);
